#!/bin/ksh
 
#-------------------------------------------------------
# Script to run the 'c' unit test on WCOSS Phase 1/2
# compute nodes.
#
# Invoke this script as follows:
# "cat run.wcoss.lsf | bsub"
#
# Output is piped to "unit_test.log"
#-------------------------------------------------------

#BSUB -oo unit_test.log
#BSUB -eo unit_test.log
#BSUB -q dev_shared
#BSUB -J ip_unit_test
#BSUB -R affinity[core]
#BSUB -R rusage[mem=100]
#BSUB -P GFS-T2O
#BSUB -W 0:01

set -x

run_unit_test.ksh

exit 0
