NCEPLIBS-ip: fftpack.F File Reference
fftpack.F File Reference
A concatination of the (FFTPACK)[https://netlib.org/fftpack/] library code.
Functions/Subroutines
subroutine csfft (isign, n, scale, x, y, table, work, isys)
csfft
subroutine dcrft (init, x, ldx, y, ldy, n, m, isign, scale, table, n1, wrk, n2, z, nz)
dcrft
subroutine drcft (init, x, ldx, y, ldy, n, m, isign, scale, table, n1, wrk, n2, z, nz)
drcft
subroutine radb2 (IDO, L1, CC, CH, WA1)
RADB2.
subroutine radb3 (IDO, L1, CC, CH, WA1, WA2)
RADB3
subroutine radb4 (IDO, L1, CC, CH, WA1, WA2, WA3)
RADB4.
subroutine radb5 (IDO, L1, CC, CH, WA1, WA2, WA3, WA4)
RADB5.
subroutine radbg (IDO, IP, L1, IDL1, CC, C1, C2, CH, CH2, WA)
RADBG.
subroutine radf2 (IDO, L1, CC, CH, WA1)
RADBG.
subroutine radf3 (IDO, L1, CC, CH, WA1, WA2)
RADF3.
subroutine radf4 (IDO, L1, CC, CH, WA1, WA2, WA3)
RADF4.
subroutine radf5 (IDO, L1, CC, CH, WA1, WA2, WA3, WA4)
RADF5.
subroutine radfg (IDO, IP, L1, IDL1, CC, C1, C2, CH, CH2, WA)
RADFG.
subroutine rfftb (N, R, WSAVE)
RFFTB.
subroutine rfftb1 (N, C, CH, WA, IFAC)
RFFTB1.
subroutine rfftf (N, R, WSAVE)
RFFTF.
subroutine rfftf1 (N, C, CH, WA, IFAC)
RFFTF1.
subroutine rffti (N, WSAVE)
RFFTI.
subroutine rffti1 (N, WA, IFAC)
RFFTI1.
subroutine scfft (isign, n, scale, x, y, table, work, isys)
scfft
subroutine scrft (init, x, ldx, y, ldy, n, m, isign, scale, table, n1, wrk, n2, z, nz)
scrft
subroutine srcft (init, x, ldx, y, ldy, n, m, isign, scale, table, n1, wrk, n2, z, nz)
srcft
Detailed Description
A concatination of the (FFTPACK)[https://netlib.org/fftpack/] library code.
FFTPACK is a package of Fortran subprograms for the fast Fourier transform of periodic and other symmetric sequences. It includes complex, real, sine, cosine, and quarter-wave transforms.
Reference:
P.N. Swarztrauber, Vectorizing the FFTs, in Parallel Computations (G. Rodrigue, ed.), Academic Press, 1982, pp. 51–83.
Author
Paul N. Swarztrauber, National Center for Atmospheric Research, Boulder, CO
Definition in file fftpack.F.
Function/Subroutine Documentation
csfft()
subroutine csfft (integer isign, integer n, real scale, real, dimension(*) x, real, dimension(*) y, real, dimension(*) table, real, dimension(*) work, integer isys)
csfft
Parameters
isign
n
scale
x
y
table
work
isys
Author
Paul N. Swarztrauber, National Center for Atmospheric Research, Boulder, CO
Definition at line 116 of file fftpack.F.
References rfftb(), and rffti().
dcrft()
subroutine dcrft (integer init, real, dimension(2*ldx,*) x, integer ldx, real, dimension(ldy,*) y, integer ldy, integer n, integer m, integer isign, real scale, real, dimension(44002) table, integer n1, real wrk, integer n2, real z, integer nz)
dcrft
Parameters
init
x
ldx
y
ldy
n
m
isign
scale
table
n1
wrk
n2
z
nz
Author
Paul N. Swarztrauber, National Center for Atmospheric Research, Boulder, CO
Definition at line 32 of file fftpack.F.
References rfftb(), and rffti().
Referenced by spffte().
drcft()
subroutine drcft (integer init, real, dimension(ldx,*) x, integer ldx, real, dimension(2*ldy,*) y, integer ldy, integer n, integer m, integer isign, real scale, real, dimension(44002) table, integer n1, real wrk, integer n2, real z, integer nz)
drcft
Parameters
init
x
ldx
y
ldy
n
m
isign
scale
table
n1
wrk
n2
z
nz
Author
Paul N. Swarztrauber, National Center for Atmospheric Research, Boulder, CO
Definition at line 158 of file fftpack.F.
References rfftf(), and rffti().
Referenced by spffte().
radb2()
subroutine radb2 (IDO, L1, dimension(ido,2,l1) CC, dimension(ido,l1,2) CH, dimension(1) WA1)
RADB2.
Parameters
IDO
L1
CC
CH
WA1
Author
Paul N. Swarztrauber, National Center for Atmospheric Research, Boulder, CO
Definition at line 530 of file fftpack.F.
Referenced by rfftb1().
radb3()
subroutine radb3 (IDO, L1, dimension(ido,3,l1) CC, dimension(ido,l1,3) CH, dimension(1) WA1, dimension(1) WA2)
RADB3
Parameters
IDO
L1
CC
CH
WA1
WA2
Author
Paul N. Swarztrauber, National Center for Atmospheric Research, Boulder, CO
Definition at line 569 of file fftpack.F.
Referenced by rfftb1().
radb4()
subroutine radb4 (IDO, L1, dimension(ido,4,l1) CC, dimension(ido,l1,4) CH, dimension(1) WA1, dimension(1) WA2, dimension(1) WA3)
RADB4.
Parameters
IDO
L1
CC
CH
WA1
WA2
WA3
Author
Paul N. Swarztrauber, National Center for Atmospheric Research, Boulder, CO
Definition at line 619 of file fftpack.F.
Referenced by rfftb1().
radb5()
subroutine radb5 (IDO, L1, dimension(ido,5,l1) CC, dimension(ido,l1,5) CH, dimension(1) WA1, dimension(1) WA2, dimension(1) WA3, dimension(1) WA4)
RADB5.
Parameters
IDO
L1
CC
CH
WA1
WA2
WA3
WA4
Author
Paul N. Swarztrauber, National Center for Atmospheric Research, Boulder, CO
Definition at line 690 of file fftpack.F.
Referenced by rfftb1().
radbg()
subroutine radbg (IDO, IP, L1, IDL1, dimension(ido,ip,l1) CC, dimension(ido,l1,ip) C1, dimension(idl1,ip) C2, dimension(ido,l1,ip) CH, dimension(idl1,ip) CH2, dimension(1) WA)
RADBG.
Parameters
IDO
IP
L1
IDL1
CC
C1
C2
CH
CH2
WA
Author
Paul N. Swarztrauber, National Center for Atmospheric Research, Boulder, CO
Definition at line 768 of file fftpack.F.
Referenced by rfftb1().
radf2()
subroutine radf2 (IDO, L1, dimension(ido,l1,2) CC, dimension(ido,2,l1) CH, dimension(1) WA1)
RADBG.
Parameters
IDO
L1
CC
CH
WA1
Author
Paul N. Swarztrauber, National Center for Atmospheric Research, Boulder, CO
Definition at line 946 of file fftpack.F.
Referenced by rfftf1().
radf3()
subroutine radf3 (IDO, L1, dimension(ido,l1,3) CC, dimension(ido,3,l1) CH, dimension(1) WA1, dimension(1) WA2)
RADF3.
Parameters
IDO
L1
CC
CH
WA1
WA2
Author
Paul N. Swarztrauber, National Center for Atmospheric Research, Boulder, CO
Definition at line 984 of file fftpack.F.
Referenced by rfftf1().
radf4()
subroutine radf4 (IDO, L1, dimension(ido,l1,4) CC, dimension(ido,4,l1) CH, dimension(1) WA1, dimension(1) WA2, dimension(1) WA3)
RADF4.
Parameters
IDO
L1
CC
CH
WA1
WA2
WA3
Author
Paul N. Swarztrauber, National Center for Atmospheric Research, Boulder, CO
Definition at line 1031 of file fftpack.F.
Referenced by rfftf1().
radf5()
subroutine radf5 (IDO, L1, dimension(ido,l1,5) CC, dimension(ido,5,l1) CH, dimension(1) WA1, dimension(1) WA2, dimension(1) WA3, dimension(1) WA4)
RADF5.
Parameters
IDO
L1
CC
CH
WA1
WA2
WA3
WA4
Author
Paul N. Swarztrauber, National Center for Atmospheric Research, Boulder, CO
Definition at line 1098 of file fftpack.F.
Referenced by rfftf1().
radfg()
subroutine radfg (IDO, IP, L1, IDL1, dimension(ido,ip,l1) CC, dimension(ido,l1,ip) C1, dimension(idl1,ip) C2, dimension(ido,l1,ip) CH, dimension(idl1,ip) CH2, dimension(1) WA)
RADFG.
Parameters
IDO
IP
L1
IDL1
CC
C1
C2
CH
CH2
WA
Author
Paul N. Swarztrauber, National Center for Atmospheric Research, Boulder, CO
Definition at line 1172 of file fftpack.F.
Referenced by rfftf1().
rfftb()
subroutine rfftb (N, dimension(1) R, dimension(1) WSAVE)
RFFTB.
Parameters
N
R
WSAVE
Author
Paul N. Swarztrauber, National Center for Atmospheric Research, Boulder, CO
Definition at line 296 of file fftpack.F.
References rfftb1().
Referenced by csfft(), dcrft(), and scrft().
rfftb1()
subroutine rfftb1 (N, dimension(1) C, dimension(1) CH, dimension(1) WA, dimension(*) IFAC)
RFFTB1.
Parameters
N
C
CH
WA
IFAC
Author
Paul N. Swarztrauber, National Center for Atmospheric Research, Boulder, CO
Definition at line 325 of file fftpack.F.
References radb2(), radb3(), radb4(), radb5(), and radbg().
Referenced by rfftb().
rfftf()
subroutine rfftf (N, dimension(1) R, dimension(1) WSAVE)
RFFTF.
Parameters
N
R
WSAVE
Author
Paul N. Swarztrauber, National Center for Atmospheric Research, Boulder, CO
Definition at line 282 of file fftpack.F.
References rfftf1().
Referenced by drcft(), scfft(), and srcft().
rfftf1()
subroutine rfftf1 (N, dimension(1) C, dimension(1) CH, dimension(1) WA, dimension(*) IFAC)
RFFTF1.
Parameters
N
C
CH
WA
IFAC
Author
Paul N. Swarztrauber, National Center for Atmospheric Research, Boulder, CO
Definition at line 394 of file fftpack.F.
References radf2(), radf3(), radf4(), radf5(), and radfg().
Referenced by rfftf().
rffti()
subroutine rffti (N, dimension(1) WSAVE)
RFFTI.
Parameters
N
WSAVE
Author
Paul N. Swarztrauber, National Center for Atmospheric Research, Boulder, CO
Definition at line 309 of file fftpack.F.
References rffti1().
Referenced by csfft(), dcrft(), drcft(), scfft(), scrft(), and srcft().
rffti1()
subroutine rffti1 (N, dimension(1) WA, dimension(*) IFAC)
RFFTI1.
Parameters
N
WA
IFAC
Author
Paul N. Swarztrauber, National Center for Atmospheric Research, Boulder, CO
Definition at line 461 of file fftpack.F.
Referenced by rffti().
scfft()
subroutine scfft (integer isign, integer n, real scale, real, dimension(*) x, real, dimension(*) y, real, dimension(*) table, real, dimension(*) work, integer isys)
scfft
Parameters
isign
n
scale
x
y
table
work
isys
Author
Paul N. Swarztrauber, National Center for Atmospheric Research, Boulder, CO
Definition at line 249 of file fftpack.F.
References rfftf(), and rffti().
scrft()
subroutine scrft (integer init, real, dimension(2*ldx,*) x, integer ldx, real, dimension(ldy,*) y, integer ldy, integer n, integer m, integer isign, real scale, real, dimension(44002) table, integer n1, real wrk, integer n2, real z, integer nz)
scrft
Parameters
init
x
ldx
y
ldy
n
m
isign
scale
table
n1
wrk
n2
z
nz
Author
Paul N. Swarztrauber, National Center for Atmospheric Research, Boulder, CO
Definition at line 78 of file fftpack.F.
References rfftb(), and rffti().
Referenced by spfft(), spfft1(), and spffte().
srcft()
subroutine srcft (integer init, real, dimension(ldx,*) x, integer ldx, real, dimension(2*ldy,*) y, integer ldy, integer n, integer m, integer isign, real scale, real, dimension(44002) table, integer n1, real wrk, integer n2, real z, integer nz)
srcft
Parameters
init
x
ldx
y
ldy
n
m
isign
scale
table
n1
wrk
n2
z
nz
Author
Paul N. Swarztrauber, National Center for Atmospheric Research, Boulder, CO
Definition at line 207 of file fftpack.F.
References rfftf(), and rffti().
Referenced by spfft(), spfft1(), and spffte().