NCEPLIBS-ip: polfix_mod Module Reference
polfix_mod Module Reference
Make multiple pole scalar values consistent.
Functions/Subroutines
subroutine, public polfixs (NM, NX, KM, RLAT, IB, LO, GO)
Make multiple pole scalar values consistent.
subroutine, public polfixv (NM, NX, KM, RLAT, RLON, IB, LO, UO, VO)
Make multiple pole vector values consistent,.
Detailed Description
Make multiple pole scalar values consistent.
Author
Iredell, Kyle Gerheiser
Function/Subroutine Documentation
polfixs()
subroutine, public polfix_mod::polfixs (integer, intent(in) NM, integer, intent(in) NX, integer, intent(in) KM, real, dimension(nm), intent(in) RLAT, integer, dimension(km), intent(in) IB, logical*1, dimension(nx,km), intent(inout) LO, real, dimension(nx,km), intent(inout) GO)
Make multiple pole scalar values consistent.
This subprogram averages multiple pole scalar values on a latitude/longitude grid. Bitmaps may be averaged too.
Parameters
[in] nm integer number of grid points
[in] nx integer leading dimension of fields
[in] km integer number of fields
[in] rlat real (no) latitudes in degrees
[in] ib integer (km) bitmap flags
[out] lo logical*1 (nx,km) bitmaps (if some ib(k)=1)
[out] go real (nx,km) fields
Author
Iredell
Date
96-04-10
Definition at line 29 of file polfix_mod.F90.
Referenced by bicubic_interp_mod::interpolate_bicubic::interpolate_bicubic_scalar(), bilinear_interp_mod::interpolate_bilinear::interpolate_bilinear_scalar(), budget_interp_mod::interpolate_budget::interpolate_budget_scalar(), neighbor_budget_interp_mod::interpolate_neighbor_budget::interpolate_neighbor_budget_scalar(), and neighbor_interp_mod::interpolate_neighbor::interpolate_neighbor_scalar().
polfixv()
subroutine, public polfix_mod::polfixv (integer, intent(in) NM, integer, intent(in) NX, integer, intent(in) KM, real, dimension(nm), intent(in) RLAT, real, dimension(nm), intent(in) RLON, integer, dimension(km), intent(in) IB, logical*1, dimension(nx,km), intent(inout) LO, real, dimension(nx,km), intent(inout) UO, real, dimension(nx,km), intent(inout) VO)
Make multiple pole vector values consistent,.
This subprogram averages multiple pole vector values on a latitude/longitude grid. Bitmaps may be averaged too. Vectors are rotated with respect to their longitude.
Parameters
[in] nm integer number of grid points
[in] nx integer leading dimension of fields
[in] km integer number of fields
[in] rlat real (nm) latitudes in degrees
[in] rlon real (nm) longitudes in degrees
[in] ib integer (km) bitmap flags
[in,out] lo logical*1 (nx,km) bitmaps (if some ib(k)=1)
[in,out] uo real (nx,km) u-winds
[in,out] vo real (nx,km) v-winds
Author
Iredell
Date
96-04-10
Definition at line 124 of file polfix_mod.F90.
Referenced by bicubic_interp_mod::interpolate_bicubic::interpolate_bicubic_vector(), bilinear_interp_mod::interpolate_bilinear::interpolate_bilinear_vector(), budget_interp_mod::interpolate_budget::interpolate_budget_vector(), neighbor_budget_interp_mod::interpolate_neighbor_budget::interpolate_neighbor_budget_vector(), and neighbor_interp_mod::interpolate_neighbor::interpolate_neighbor_vector().