NCEPLIBS-ip: ip_equid_cylind_grid_mod Module Reference
ip_equid_cylind_grid_mod Module Reference
Equidistant cylindrical grib decoder and grid coordinate transformations.
Data Types
type ip_equid_cylind_grid
Functions/Subroutines
subroutine equid_cylind_grid_area (rlat, area)
Computes the grid box area for a equidistant cylindrical grid.
subroutine equid_cylind_map_jacob (xlon, xlat, ylon, ylat)
Computes the map jacobians for a equidistant cylindrical grid.
subroutine equid_cylind_vect_rot (crot, srot)
Computes the vector rotation sines and cosines for a equidistant cylindrical grid.
subroutine gdswzd_equid_cylind (self, iopt, npts, fill, xpts, ypts, rlon, rlat, nret, crot, srot, xlon, xlat, ylon, ylat, area)
Calculates Earth coordinates (iopt = 1) or grid coorindates (iopt = -1) for equidistant cylindrical grids.
subroutine init_grib1 (self, g1_desc)
Initializes an equidistant cylindrical grid given a grib1_descriptor object.
subroutine init_grib2 (self, g2_desc)
Initializes an equidistant cylindrical grid given a grib2_descriptor object.
Variables
real dlat
Grid resolution in degrees n/s direction.
real dlon
Grid resolution in degrees e/w direction.
real rerth
Radius of the Earth.
Detailed Description
Equidistant cylindrical grib decoder and grid coordinate transformations.
Octet numbers refer to [GRIB2 - GRID DEFINITION TEMPLATE 3.0 Latitude/Longitude or equidistant cylindrical, or Plate Carree](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp3-0.shtml).
Author
George Gayno, Mark Iredell, Kyle Gerheiser
Date
July 2021
Function/Subroutine Documentation
equid_cylind_grid_area()
subroutine ip_equid_cylind_grid_mod::equid_cylind_grid_area (real, intent(in) rlat, real, intent(out) area) private
Computes the grid box area for a equidistant cylindrical grid.
Parameters
[in] rlat Latitude of grid point in degrees.
[out] area Area weights in m^2.
Author
Mark Iredell, George Gayno
Date
July 2021
Definition at line 363 of file ip_equid_cylind_grid_mod.F90.
References dlat, dlon, and rerth.
Referenced by gdswzd_equid_cylind().
equid_cylind_map_jacob()
subroutine ip_equid_cylind_grid_mod::equid_cylind_map_jacob (real, intent(out) xlon, real, intent(out) xlat, real, intent(out) ylon, real, intent(out) ylat) private
Computes the map jacobians for a equidistant cylindrical grid.
Parameters
[out] xlon dx/dlon in 1/degrees.
[out] xlat dx/dlat in 1/degrees.
[out] ylon dy/dlon in 1/degrees.
[out] ylat dy/dlat in 1/degrees.
Author
George Gayno
Date
July 2021
Definition at line 346 of file ip_equid_cylind_grid_mod.F90.
References dlat, and dlon.
Referenced by gdswzd_equid_cylind().
equid_cylind_vect_rot()
subroutine ip_equid_cylind_grid_mod::equid_cylind_vect_rot (real, intent(out) crot, real, intent(out) srot) private
Computes the vector rotation sines and cosines for a equidistant cylindrical grid.
Parameters
[out] crot Clockwise vector rotation cosines.
[out] srot Clockwise vector rotation sines.
Note
ugrid=crot*uearth-srot*vearth;
vgrid=srot*uearth+crot*vearth
Author
George Gayno
Date
July 2021
Definition at line 327 of file ip_equid_cylind_grid_mod.F90.
Referenced by gdswzd_equid_cylind().
gdswzd_equid_cylind()
subroutine ip_equid_cylind_grid_mod::gdswzd_equid_cylind (class(ip_equid_cylind_grid), intent(in) self, integer, intent(in) iopt, integer, intent(in) npts, real, intent(in) fill, real, dimension(npts), intent(inout) xpts, real, dimension(npts), intent(inout) ypts, real, dimension(npts), intent(inout) rlon, real, dimension(npts), intent(inout) rlat, integer, intent(out) nret, real, dimension(npts), intent(out), optional crot, real, dimension(npts), intent(out), optional srot, real, dimension(npts), intent(out), optional xlon, real, dimension(npts), intent(out), optional xlat, real, dimension(npts), intent(out), optional ylon, real, dimension(npts), intent(out), optional ylat, real, dimension(npts), intent(out), optional area) private
Calculates Earth coordinates (iopt = 1) or grid coorindates (iopt = -1) for equidistant cylindrical grids.
If the selected coordinates are more than one gridpoint beyond the the edges of the grid domain, then the relevant output elements are set to fill values.
The actual number of valid points computed is returned too. Optionally, the vector rotations, the map jacobians and the grid box areas may be returned as well.
To compute the vector rotations, the optional arguments 'srot' and 'crot' must be present.
To compute the map jacobians, the optional arguments 'xlon', 'xlat', 'ylon', 'ylat' must be present.
To compute the grid box areas, the optional argument 'area' must be present.
Parameters
[in] self The grid object gdswzd was called on.
[in] iopt option flag
+1 to compute earth coords of selected grid coords.
-1 o compute grid coords of selected earth coords.
[in] npts Maximum number of coordinates.
[in] fill Fill value to set invalid output data. Must be impossible value; suggested value: -9999.
[in,out] xpts Grid x point coordinates if iopt>0.
[in,out] ypts Grid y point coordinates if iopt>0.
[in,out] rlon Earth longitudes in degrees e if iopt<0 (Acceptable range: -360. to 360.)
[in,out] rlat Earth latitudes in degrees n if iopt<0 (Acceptable range: -90. to 90.)
[out] nret Number of valid points computed.
[out] crot Optional clockwise vector rotation cosines.
[out] srot Optional clockwise vector rotation sines.
[out] xlon Optional dx/dlon in 1/degrees.
[out] xlat Optional dx/dlat in 1/degrees.
[out] ylon Optional dy/dlon in 1/degrees.
[out] ylat Optional dy/dlat in 1/degrees.
[out] area Optional area weights in m**2.
Author
Mark Iredell, George Gayno, Kyle Gerheiser
Date
July 2021
Definition at line 203 of file ip_equid_cylind_grid_mod.F90.
References dlat, dlon, equid_cylind_grid_area(), equid_cylind_map_jacob(), equid_cylind_vect_rot(), and rerth.
init_grib1()
subroutine ip_equid_cylind_grid_mod::init_grib1 (class(ip_equid_cylind_grid), intent(inout) self, type(grib1_descriptor), intent(in) g1_desc) private
Initializes an equidistant cylindrical grid given a grib1_descriptor object.
Parameters
[in,out] self The grid to initialize
[in] g1_desc A grib1_descriptor
Author
Kyle Gerheiser
Date
July 2021
Definition at line 53 of file ip_equid_cylind_grid_mod.F90.
init_grib2()
subroutine ip_equid_cylind_grid_mod::init_grib2 (class(ip_equid_cylind_grid), intent(inout) self, type(grib2_descriptor), intent(in) g2_desc) private
Initializes an equidistant cylindrical grid given a grib2_descriptor object.
Parameters
[in,out] self The grid to initialize
[in] g2_desc A grib2_descriptor
Author
Kyle Gerheiser
Date
July 2021
Definition at line 109 of file ip_equid_cylind_grid_mod.F90.
Variable Documentation
dlat
real ip_equid_cylind_grid_mod::dlat
Grid resolution in degrees n/s direction.
Definition at line 40 of file ip_equid_cylind_grid_mod.F90.
Referenced by equid_cylind_grid_area(), equid_cylind_map_jacob(), and gdswzd_equid_cylind().
dlon
real ip_equid_cylind_grid_mod::dlon private
Grid resolution in degrees e/w direction.
Definition at line 41 of file ip_equid_cylind_grid_mod.F90.
Referenced by equid_cylind_grid_area(), equid_cylind_map_jacob(), and gdswzd_equid_cylind().
rerth
real ip_equid_cylind_grid_mod::rerth private
Radius of the Earth.
Definition at line 42 of file ip_equid_cylind_grid_mod.F90.
Referenced by equid_cylind_grid_area(), and gdswzd_equid_cylind().