NCEPLIBS-ip: spfftpt.f File Reference
spfftpt.f File Reference
Compute fourier transform to gridpoints.
Functions/Subroutines
subroutine spfftpt (M, N, INCW, INCG, KMAX, RLON, W, G)
This subprogram computes a slow Fourier transform from Fourier space to a set of gridpoints.
Detailed Description
Compute fourier transform to gridpoints.
Author
Iredell
Date
96-02-20
Definition in file spfftpt.f.
Function/Subroutine Documentation
spfftpt()
subroutine spfftpt (integer, intent(in) M, integer, intent(in) N, integer, intent(in) INCW, integer, intent(in) INCG, integer, intent(in) KMAX, real, dimension(n), intent(in) RLON, real, dimension(2*incw,kmax), intent(in) W, real, dimension(incg,kmax), intent(out) G)
This subprogram computes a slow Fourier transform from Fourier space to a set of gridpoints.
Note
This subprogram is thread-safe.
Parameters
M Fourier wavenumber truncation
N number of gridpoints
INCW first dimension of the complex amplitude array (INCW >= M+1)
INCG first dimension of the gridpoint array (INCG >= N)
KMAX number of Fourier fields
RLON grid longitudes in degrees
W Fourier amplitudes
G gridpoint values
Author
Iredell
Date
96-02-20
Definition at line 22 of file spfftpt.f.
Referenced by sptgpt(), sptgptsd(), sptgptv(), and sptgptvd().