NCEPLIBS-ip: splat.F File Reference
splat.F File Reference
Computes cosines of colatitude and Gaussian weights for sets of latitudes.
Functions/Subroutines
subroutine splat (IDRT, JMAX, SLAT, WLAT)
Computes cosines of colatitude and Gaussian weights for one of the following specific global sets of latitudes.
Detailed Description
Computes cosines of colatitude and Gaussian weights for sets of latitudes.
Program History Log
Date Programmer Comments
96-02-20 Iredell Initial.
97-10-20 Iredell Adjust precision.
98-06-11 Iredell Generalize precision using FORTRAN 90 intrinsic.
1998-12-03 Iredell Generalize precision further.
1998-12-03 Iredell Uses AIX ESSL BLAS calls.
2009-12-27 D. Stark Updated to switch between ESSL calls on an AIX platform, and Numerical Recipies calls elsewise.
2010-12-30 Slovacek Update alignment so preprocessor does not cause compilation failure.
2012-09-01 E. Mirvis & M.Iredell Merging & debugging linux errors of _d and _8 using generic LU factorization.
2012-11-05 E. Mirvis Generic FFTPACK and LU lapack were removed.
Author
Iredell
Date
96-02-20
Definition in file splat.F.
Function/Subroutine Documentation
splat()
subroutine splat (IDRT, JMAX, real, dimension(jmax) SLAT, real, dimension(jmax) WLAT)
Computes cosines of colatitude and Gaussian weights for one of the following specific global sets of latitudes.
Gaussian latitudes (IDRT=4)
Equally-spaced latitudes including poles (IDRT=0)
Equally-spaced latitudes excluding poles (IDRT=256)
The Gaussian latitudes are located at the zeroes of the Legendre polynomial of the given order. These latitudes are efficient for reversible transforms from spectral space. (About twice as many equally-spaced latitudes are needed.) The weights for the equally-spaced latitudes are based on Ellsaesser (JAM,1966). (No weight is given the pole point.) Note that when analyzing grid to spectral in latitude pairs, if an equator point exists, its weight should be halved. This version invokes the ibm essl matrix solver.
Parameters
[in] IDRT grid identifier
4 for Gaussian grid
0 for equally-spaced grid including poles
256 for equally-spaced grid excluding poles
[in] JMAX number of latitudes
[out] SLAT sines of latitude
[out] WLAT Gaussian weights
Author
Iredell
Date
96-02-20
Definition at line 45 of file splat.F.
References lubksb(), and ludcmp().
Referenced by ip_gaussian_grid_mod::gdswzd_gaussian(), and sptranf0().