NCEPLIBS-ip: spsynth.f File Reference
spsynth.f File Reference
Synthesize Fourier coefficients from spectral coefficients.
Functions/Subroutines
subroutine spsynth (I, M, IM, IX, NC, NCTOP, KM, CLAT, PLN, PLNTOP, MP, SPC, SPCTOP, F)
Synthesizes Fourier coefficients from spectral coefficients for a latitude pair (Northern and Southern hemispheres).
Detailed Description
Synthesize Fourier coefficients from spectral coefficients.
Program History Log
Date Programmer Comments
91-10-31 Mark Iredell Initial.
1998-12-18 Mark Iredell Include scalar and gradient option.
Author
Iredell
Date
92-10-31
Definition in file spsynth.f.
Function/Subroutine Documentation
spsynth()
subroutine spsynth (I, M, IM, IX, NC, NCTOP, KM, CLAT, real, dimension((m+1)*((i+1)*m+2)/2) PLN, real, dimension(m+1) PLNTOP, integer, dimension(km) MP, real, dimension(nc,km) SPC, real, dimension(nctop,km) SPCTOP, real, dimension(ix,2,km) F)
Synthesizes Fourier coefficients from spectral coefficients for a latitude pair (Northern and Southern hemispheres).
Vector components are divided by cosine of latitude.
Parameters
I spectral domain shape (0 for triangular, 1 for rhomboidal)
M spectral truncation
IM even number of Fourier coefficients
IX dimension of Fourier coefficients (IX>=IM+2)
NC dimension of spectral coefficients (NC>=(M+1)*((I+1)*M+2))
NCTOP dimension of spectral coefficients over top (NCTOP>=2*(M+1))
KM number of fields
CLAT cosine of latitude
PLN ((M+1)*((I+1)*M+2)/2) Legendre polynomial
PLNTOP Legendre polynomial over top
SPC spectral coefficients
SPCTOP spectral coefficients over top
MP identifiers (0 for scalar, 1 for vector, or 10 for scalar and gradient)
F Fourier coefficients for latitude pair
Author
Iredell
Date
92-10-31
Definition at line 37 of file spsynth.f.
Referenced by sptgpm(), sptgpmv(), sptgps(), sptgpsv(), sptgpt(), sptgptsd(), sptgptv(), sptgptvd(), and sptranf1().