NCEPLIBS-ip: sptgpsv.f File Reference
sptgpsv.f File Reference
Transform spectral vector to polar stereo.
Functions/Subroutines
subroutine sptgpsv (IROMB, MAXWV, KMAX, NPS, KWSKIP, KGSKIP, NISKIP, NJSKIP, TRUE, XMESH, ORIENT, WAVED, WAVEZ, UN, VN, US, VS)
This subprogram performs a spherical transform from spectral coefficients of divergences and curls to vector fields on a pair of polar stereographic grids.
Detailed Description
Transform spectral vector to polar stereo.
Program History Log
Date Programmer Comments
96-02-29 Iredell Initial.
1998-12-15 Iredell Openmp directives inserted.
Author
Iredell
Date
96-02-29
Definition in file sptgpsv.f.
Function/Subroutine Documentation
sptgpsv()
subroutine sptgpsv (IROMB, MAXWV, KMAX, NPS, KWSKIP, KGSKIP, NISKIP, NJSKIP, TRUE, XMESH, ORIENT, real, dimension(*) WAVED, real, dimension(*) WAVEZ, real, dimension(*) UN, real, dimension(*) VN, real, dimension(*) US, real, dimension(*) VS)
This subprogram performs a spherical transform from spectral coefficients of divergences and curls to vector fields on a pair of polar stereographic grids.
The wave-space can be either triangular or rhomboidal.
The wave and grid fields may have general indexing, but each wave field is in sequential 'IBM order', i.e. with zonal wavenumber as the slower index.
The two square polar stereographic grids are centered on the respective poles, with the orientation longitude of the southern hemisphere grid 180 degrees opposite that of the northern hemisphere grid.
The vectors are automatically rotated to be resolved relative to the respective polar stereographic grids.
The transform is made efficient by combining points in eight sectors of each polar stereographic grid,
numbered as in the diagram below. The pole and the sector boundaries
are treated specially in the code.
Unfortunately, this approach induces some hairy indexing and code loquacity, for which the developer apologizes.
              \ 4 | 5 /
               \  |  /
              3 \ | / 6
                 |/
              ----+----
                 /|\
              2 / | \ 7
               /  |  \
              / 1 | 8 \
The transforms are all multiprocessed over sector points. transform several fields at a time to improve vectorization. subprogram can be called from a multiprocessing environment.
Parameters
IROMB spectral domain shape (0 for triangular, 1 for rhomboidal)
MAXWV spectral truncation
KMAX number of fields to transform.
NPS odd order of the polar stereographic grids
KWSKIP skip number between wave fields (defaults to (MAXWV+1)*((IROMB+1)*MAXWV+2) if KWSKIP=0)
KGSKIP skip number between grid fields (defaults to NPS*NPS if KGSKIP=0)
NISKIP skip number between grid i-points (defaults to 1 if NISKIP=0)
NJSKIP skip number between grid j-points (defaults to NPS if NJSKIP=0)
TRUE latitude at which ps grid is true (usually 60.)
XMESH grid length at true latitude (m)
ORIENT longitude at bottom of northern ps grid (southern ps grid will have opposite orientation.)
WAVED wave divergence fields
WAVEZ wave vorticity fields
UN northern polar stereographic u-winds
VN northern polar stereographic v-winds
US southern polar stereographic u-winds
VS southern polar stereographic v-winds
Author
Iredell
Date
96-02-29
Definition at line 80 of file sptgpsv.f.
References spdz2uv(), splegend(), spsynth(), and spwget().
Referenced by sptgpsd(), and sptrunsv().