NCEPLIBS-ip: sptgptsd.f File Reference
sptgptsd.f File Reference
Transform spectral scalar to station points.
Functions/Subroutines
subroutine sptgptsd (IROMB, MAXWV, KMAX, NMAX, KWSKIP, KGSKIP, NRSKIP, NGSKIP, RLAT, RLON, WAVE, GP, XP, YP)
This subprogram performs a spherical transform from spectral coefficients of scalar quantities to specified sets of station point values and their gradients on the globe.
Detailed Description
Transform spectral scalar to station points.
Author
Iredell
Date
96-02-29
Program History Log
Date Programmer Comments
96-02-29 Iredell Initial.
1998-12-15 Iredell Openmp directives inserted.
1999-08-18 Iredell Openmp directive typo fixed.
Author
Iredell
Date
96-02-29
Definition in file sptgptsd.f.
Function/Subroutine Documentation
sptgptsd()
subroutine sptgptsd (IROMB, MAXWV, KMAX, NMAX, KWSKIP, KGSKIP, NRSKIP, NGSKIP, real, dimension(*) RLAT, real, dimension(*) RLON, real, dimension(*) WAVE, real, dimension(*) GP, real, dimension(*) XP, real, dimension(*) YP)
This subprogram performs a spherical transform from spectral coefficients of scalar quantities to specified sets of station point values and their gradients on the globe.
The wave-space can be either triangular or rhomboidal.
The wave and point fields may have general indexing, but each wave field is in sequential 'IBM order', i.e. with zonal wavenumber as the slower index.
The transforms are all multiprocessed over stations.
Transform several fields at a time to improve vectorization.
Subprogram can be called from a multiprocessing environment.
Parameters
IROMB spectral domain shape (0 for triangular, 1 for rhomboidal)
MAXWV spectral truncation
KMAX number of fields to transform.
NMAX number of station points to return
KWSKIP skip number between wave fields (defaults to (MAXWV+1)*((IROMB+1)*MAXWV+2) if KWSKIP=0)
KGSKIP skip number between station point sets (defaults to NMAX if KGSKIP=0)
NRSKIP skip number between station lats and lons (defaults to 1 if NRSKIP=0)
NGSKIP skip number between station points (defaults to 1 if NGSKIP=0)
RLAT station latitudes in degrees
RLON station longitudes in degrees
WAVE wave fields
GP station point sets
XP station point x-gradient sets
YP station point y-gradient sets
Author
Iredell
Date
96-02-29
Definition at line 52 of file sptgptsd.f.
References spfftpt(), spgradx(), spgrady(), splegend(), spsynth(), and spwget().