NCEPLIBS-ip: sptgptvd.f File Reference
sptgptvd.f File Reference
Transform spectral vector to station points.
Functions/Subroutines
subroutine sptgptvd (IROMB, MAXWV, KMAX, NMAX, KWSKIP, KGSKIP, NRSKIP, NGSKIP, RLAT, RLON, WAVED, WAVEZ, DP, ZP, UP, VP, UXP, VXP, UYP, VYP)
This subprogram performs a spherical transform from spectral coefficients of divergences and curls to specified sets of station point vectors and their gradients on the globe.
Detailed Description
Transform spectral vector to station points.
Program History Log
Date Programmer Comments
96-02-29 Iredell Initial.
1998-12-15 Iredell Openmp directives inserted.
1999-08-18 Iredell Openmp directive typo fixed.
Author
Iredell
Date
96-02-29
Definition in file sptgptvd.f.
Function/Subroutine Documentation
sptgptvd()
subroutine sptgptvd (IROMB, MAXWV, KMAX, NMAX, KWSKIP, KGSKIP, NRSKIP, NGSKIP, real, dimension(*) RLAT, real, dimension(*) RLON, real, dimension(*) WAVED, real, dimension(*) WAVEZ, real, dimension(*) DP, real, dimension(*) ZP, real, dimension(*) UP, real, dimension(*) VP, real, dimension(*) UXP, real, dimension(*) VXP, real, dimension(*) UYP, real, dimension(*) VYP)
This subprogram performs a spherical transform from spectral coefficients of divergences and curls to specified sets of station point vectors and their gradients on the globe.
 DP=(D(UP)/DLON+D(VP*CLAT)/DLAT)/(R*CLAT)
 ZP=(D(VP)/DLON-D(UP*CLAT)/DLAT)/(R*CLAT)
 UXP=D(UP*CLAT)/DLON/(R*CLAT)
 VXP=D(VP*CLAT)/DLON/(R*CLAT)
 UYP=D(UP*CLAT)/DLAT/R
 VYP=D(VP*CLAT)/DLAT/R
The wave-space can be either triangular or rhomboidal.
The wave and point fields may have general indexing, but each wave field is in sequential 'IBM order', i.e. with zonal wavenumber as the slower index.
The transforms are all multiprocessed over stations.
Transform several fields at a time to improve vectorization.
Subprogram can be called from a multiprocessing environment.
Parameters
IROMB spectral domain shape (0 for triangular, 1 for rhomboidal)
MAXWV spectral truncation
KMAX number of fields to transform.
NMAX number of station points to return
KWSKIP skip number between wave fields (defaults to (MAXWV+1)*((IROMB+1)*MAXWV+2) IF KWSKIP=0)
KGSKIP skip number between station point sets (defaults to NMAX if KGSKIP=0)
NRSKIP skip number between station lats and lons (defaults to 1 if NRSKIP=0)
NGSKIP skip number between station points (defaults to 1 if NGSKIP=0)
RLAT station latitudes in degrees
RLON station longitudes in degrees
WAVED wave divergence fields
WAVEZ wave vorticity fields
DP station point divergence sets
ZP station point vorticity sets
UP station point u-wind sets
VP station point v-wind sets
UXP station point u-wind x-gradient sets
VXP station point v-wind x-gradient sets
UYP station point u-wind y-gradient sets
VYP station point v-wind y-gradient sets
Author
Iredell
Date
96-02-29
Definition at line 66 of file sptgptvd.f.
References spdz2uv(), spfftpt(), spgradx(), splegend(), spsynth(), and spwget().