NCEPLIBS-ip: sptranf1.f File Reference
sptranf1.f File Reference
Sptranf spectral transform.
Functions/Subroutines
subroutine sptranf1 (IROMB, MAXWV, IDRT, IMAX, JMAX, JB, JE, EPS, EPSTOP, ENN1, ELONN1, EON, EONTOP, AFFT, CLAT, SLAT, WLAT, PLN, PLNTOP, MP, W, WTOP, G, IDIR)
This subprogram performs an single latitude transform for subprogram sptranf().
Detailed Description
Sptranf spectral transform.
Author
Iredell
Date
96-02-29
Definition in file sptranf1.f.
Function/Subroutine Documentation
sptranf1()
subroutine sptranf1 (IROMB, MAXWV, IDRT, IMAX, JMAX, JB, JE, real, dimension((maxwv+1)*((iromb+1)*maxwv+2)/2) EPS, real, dimension(maxwv+1) EPSTOP, real, dimension((maxwv+1)*((iromb+1)*maxwv+2)/2) ENN1, real, dimension((maxwv+1)*((iromb+1)*maxwv+2)/2) ELONN1, real, dimension((maxwv+1)*((iromb+1)*maxwv+2)/2) EON, real, dimension(maxwv+1) EONTOP, real(8), dimension(50000+4*imax) AFFT, real, dimension(jb:je) CLAT, real, dimension(jb:je) SLAT, real, dimension(jb:je) WLAT, real, dimension((maxwv+1)*((iromb+1)*maxwv+2)/2,jb:je) PLN, real, dimension(maxwv+1,jb:je) PLNTOP, MP, real, dimension((maxwv+1)*((iromb+1)*maxwv+2)) W, real, dimension(2*(maxwv+1)) WTOP, real, dimension(imax,2,jb:je) G, IDIR)
This subprogram performs an single latitude transform for subprogram sptranf().
Use this subprogram outside the sptranf() family context at your own risk.
Parameters
IROMB spectral domain shape (0 for triangular, 1 for rhomboidal)
MAXWV spectral truncation
IDRT grid identifier
IDRT=4 for Gaussian grid,
IDRT=0 for equally-spaced grid including poles,
IDRT=256 for equally-spaced grid excluding poles
IMAX even number of longitudes
JMAX number of latitudes
JB latitude index (from pole) to begin transform
JE latitude index (from pole) to end transform
EPS
EPSTOP
ENN1
ELONN1
EON
EONTOP
CLAT cosines of latitude
SLAT sines of latitude
WLAT Gaussian weights
AFFT auxiliary array if IDIR=0
PLN Legendre polynomials
PLNTOP Legendre polynomial over top
MP identifier (0 for scalar, 1 for vector)
[out] W wave field if IDIR>0
[out] WTOP wave field over top if IDIR>0
[out] G grid field if IDIR<0
IDIR transform flag (IDIR>0 for wave to grid, IDIR<0 for grid to wave)
Author
Iredell
Date
96-02-29
Definition at line 40 of file sptranf1.f.
References spanaly(), spffte(), and spsynth().
Referenced by sptranf(), and sptranfv().