NCEPLIBS-ip: sptranf0.f File Reference
sptranf0.f File Reference
Sptranf spectral initialization.
Functions/Subroutines
subroutine sptranf0 (IROMB, MAXWV, IDRT, IMAX, JMAX, JB, JE, EPS, EPSTOP, ENN1, ELONN1, EON, EONTOP, AFFT, CLAT, SLAT, WLAT, PLN, PLNTOP)
This subprogram performs an initialization for subprogram sptranf().
Detailed Description
Sptranf spectral initialization.
Author
IREDELL
Date
96-02-29
Definition in file sptranf0.f.
Function/Subroutine Documentation
sptranf0()
subroutine sptranf0 (IROMB, MAXWV, IDRT, IMAX, JMAX, JB, JE, real, dimension((maxwv+1)*((iromb+1)*maxwv+2)/2) EPS, real, dimension(maxwv+1) EPSTOP, real, dimension((maxwv+1)*((iromb+1)*maxwv+2)/2) ENN1, real, dimension((maxwv+1)*((iromb+1)*maxwv+2)/2) ELONN1, real, dimension((maxwv+1)*((iromb+1)*maxwv+2)/2) EON, real, dimension(maxwv+1) EONTOP, real(8), dimension(50000+4*imax) AFFT, real, dimension(jb:je) CLAT, real, dimension(jb:je) SLAT, real, dimension(jb:je) WLAT, real, dimension((maxwv+1)*((iromb+1)*maxwv+2)/2,jb:je) PLN, real, dimension(maxwv+1,jb:je) PLNTOP)
This subprogram performs an initialization for subprogram sptranf().
Use this subprogram outside the sptranf() family context at your own risk.
Parameters
IROMB spectral domain shape (0 for triangular, 1 for rhomboidal)
MAXWV spectral truncation
IDRT grid identifier
IDRT=4 for Gaussian grid,
IDRT=0 for equally-spaced grid including poles,
IDRT=256 for equally-spaced grid excluding poles
IMAX even number of longitudes
JMAX number of latitudes
JB latitude index (from pole) to begin transform
JE latitude index (from pole) to end transform
EPS
EPSTOP
ENN1
ELONN1
EON
EONTOP
AFFT auxiliary array if IDIR=0
CLAT cosines of latitude
SLAT sines of latitude
WLAT Gaussian weights
PLN Legendre polynomials
PLNTOP Legendre polynomial over top
Author
IREDELL
Date
96-02-29
Definition at line 34 of file sptranf0.f.
References spffte(), splat(), splegend(), and spwget().
Referenced by sptranf(), and sptranfv().