NCEPLIBS-ip: spwget.f File Reference
spwget.f File Reference
Get wave-space constants.
Functions/Subroutines
subroutine spwget (IROMB, MAXWV, EPS, EPSTOP, ENN1, ELONN1, EON, EONTOP)
This subprogram gets wave-space constants.
Detailed Description
Get wave-space constants.
Author
Iredell
Date
96-02-29
Definition in file spwget.f.
Function/Subroutine Documentation
spwget()
subroutine spwget (IROMB, MAXWV, real, dimension((maxwv+1)*((iromb+1)*maxwv+2)/2) EPS, real, dimension(maxwv+1) EPSTOP, real, dimension((maxwv+1)*((iromb+1)*maxwv+2)/2) ENN1, real, dimension((maxwv+1)*((iromb+1)*maxwv+2)/2) ELONN1, real, dimension((maxwv+1)*((iromb+1)*maxwv+2)/2) EON, real, dimension(maxwv+1) EONTOP)
This subprogram gets wave-space constants.
Parameters
IROMB spectral domain shape (0 for triangular, 1 for rhomboidal)
MAXWV spectral truncation
EPS
EPSTOP
ENN1
ELONN1
EON
EONTOP
Author
Iredell
Date
96-02-29
Definition at line 17 of file spwget.f.
References speps().
Referenced by sptgpm(), sptgpmd(), sptgpmv(), sptgps(), sptgpsd(), sptgpsv(), sptgpt(), sptgptd(), sptgptsd(), sptgptv(), sptgptvd(), sptrand(), sptranf0(), sptrungv(), sptrunl(), sptrunmv(), sptrunsv(), and sptrunv().