NCEPLIBS-ip: movect.F90 File Reference
movect.F90 File Reference
Move a vector along a great circle.
Functions/Subroutines
subroutine movect (FLAT, FLON, TLAT, TLON, CROT, SROT)
This subprogram provides the rotation parameters to move a vector along a great circle from one position to another while conserving its orientation with respect to the great circle.
Detailed Description
Move a vector along a great circle.
Author
Iredell
Date
96-04-10
Definition in file movect.F90.
Function/Subroutine Documentation
movect()
subroutine movect (real, intent(in) FLAT, real, intent(in) FLON, real, intent(in) TLAT, real, intent(in) TLON, real, intent(out) CROT, real, intent(out) SROT)
This subprogram provides the rotation parameters to move a vector along a great circle from one position to another while conserving its orientation with respect to the great circle.
These rotation parameters are useful for vector interpolation.
Program History Log
Date Programmer Comments
96-04-10 Iredell Initial
1999-04-08 Iredell generalize precision
Parameters
[in] flat real latitude in degrees from which to move the vector.
[in] flon real longitude in degrees from which to move the vector.
[in] tlat real latitude in degrees to which to move the vector.
[in] tlon real longitude in degrees to which to move the vector.
[out] crot real clockwise vector rotation cosine.
[out] srot real clockwise vector rotation sine. (uto=crot*ufrom-srot*vfrom; vto=srot*ufrom+crot*vfrom)
Author
Iredell
Date
96-04-10
Definition at line 25 of file movect.F90.
Referenced by bicubic_interp_mod::interpolate_bicubic::interpolate_bicubic_vector(), bilinear_interp_mod::interpolate_bilinear::interpolate_bilinear_vector(), budget_interp_mod::interpolate_budget::interpolate_budget_vector(), neighbor_budget_interp_mod::interpolate_neighbor_budget::interpolate_neighbor_budget_vector(), and neighbor_interp_mod::interpolate_neighbor::interpolate_neighbor_vector().