#!/bin/bash
 
#-----------------------------------------------------
# Script to run the copygb2 regression test on WCOSS-
# Phase 3 - Dell.
#
# Invoke this script as follows:
# "cat run.wcoss-dell.lsf | bsub"
#-----------------------------------------------------

#BSUB -oo copygb2.log
#BSUB -eo copygb2.log
#BSUB -q dev_shared
#BSUB -J copygb2
#BSUB -R affinity[core(1)]
#BSUB -R rusage[mem=2500]
#BSUB -P GFS-T2O
#BSUB -W 0:20

set -x

module purge
module load EnvVars/1.0.2
module load ips/18.0.1.163
module load lsf/10.1

export REG_DIR=${LS_SUBCWD}/../..

export WORK_DIR="/gpfs/dell1/stmp/$LOGNAME/regression"

$REG_DIR/copygb2/scripts/copygb2.ksh

exit 0
