 SUBROUTINE EARTH_RADIUS(IGDTMPL, IGDTLEN, RADIUS, ECCEN_SQUARED)
!$$$  SUBPROGRAM DOCUMENTATION BLOCK
!
! SUBPROGRAM:  EARTH_RADIUS   DETERMINE EARTH RADIUS AND SHAPE
!   PRGMMR: GAYNO    ORG: W/NMC23     DATE: 2015-07-14
!
! ABSTRACT: DETERMINE THE RADIUS AND SHAPE OF THE EARTH FROM
!   THE GRIB 2 GRID DEFINITION TEMPLATE ARRAY - SECTION 3
!   OCTET 15.
!
! PROGRAM HISTORY LOG:
! 2015-07-14  GAYNO
!
! USAGE:   CALL EARTH_RADIUS(IGDTMPL, IGDTLEN, &
!                            RADIUS, ECCEN_SQUARED)
!
!   INPUT ARGUMENT LIST:
!     IGDTMPL  - INTEGER (IGDTLEN) GRID DEFINITION TEMPLATE ARRAY.
!                CORRESPONDS TO THE GFLD%IGDTMPL COMPONENT
!                OF THE NCEP G2 LIBRARY GRIDMOD DATA STRUCTURE.
!     IGDTLEN  - INTEGER NUMBER OF ELEMENTS OF THE GRID DEFINITION
!                TEMPLATE ARRAY.  CORRESPONDS TO THE GFLD%IGDTLEN
!                COMPONENT OF THE NCEP G2 LIBRARY GRIDMOD 
!                DATA STRUCTURE.
!
!   OUTPUT ARGUMENT LIST:
!     RADIUS        - REAL EARTH RADIUS IN METERS
!     ECCEN_SQUARED - REAL EARTH ECCENTRICITY SQUARED
!
! ATTRIBUTES:
!   LANGUAGE: FORTRAN 90
!
!$$$
 IMPLICIT NONE
!
 INTEGER,                INTENT(IN   ) :: IGDTLEN
 INTEGER,                INTENT(IN   ) :: IGDTMPL(IGDTLEN)
!
 REAL,                   INTENT(  OUT) :: ECCEN_SQUARED
 REAL,                   INTENT(  OUT) :: RADIUS
!
 SELECT CASE (IGDTMPL(1))
   CASE (0)
     RADIUS        = 6.367470E6
     ECCEN_SQUARED = 0.0
   CASE (5)  ! WGS84 DATUM
     RADIUS        = 6.378137E6
     ECCEN_SQUARED = 0.00669437999013
   CASE (6)
     RADIUS        = 6.3712E6
     ECCEN_SQUARED = 0.0
   CASE DEFAULT
     RADIUS        = -9999.
     ECCEN_SQUARED = -9999.
 END SELECT
!
 RETURN
!
 END SUBROUTINE EARTH_RADIUS
