 SUBROUTINE EARTH_RADIUS(IGDTMPL,IGDTLEN,RADIUS,ECCEN_SQUARED)

 IMPLICIT NONE

 INTEGER                               :: IGDTLEN
 INTEGER(KIND=4),        INTENT(IN   ) :: IGDTMPL(IGDTLEN)

 REAL,                   INTENT(  OUT) :: ECCEN_SQUARED
 REAL,                   INTENT(  OUT) :: RADIUS

 SELECT CASE (IGDTMPL(1))
   CASE (0)
     RADIUS        = 6.367470E6
     ECCEN_SQUARED = 0.0
   CASE (5)  ! WGS84 DATUM
     RADIUS        = 6.378137E6
     ECCEN_SQUARED = 0.00669437999013
   CASE (6)
     RADIUS        = 6.3712E6
     ECCEN_SQUARED = 0.0
   CASE DEFAULT
     RADIUS        = -9999.
     ECCEN_SQUARED = -9999.
 END SELECT

 RETURN

 END SUBROUTINE EARTH_RADIUS
