 SUBROUTINE EARTH_RADIUS(IGDTMPL,IGDTLEN,RADIUS)

 IMPLICIT NONE

 INTEGER                               :: IGDTLEN
 INTEGER(KIND=4),        INTENT(IN   ) :: IGDTMPL(IGDTLEN)

 REAL,                   INTENT(  OUT) :: RADIUS

 SELECT CASE (IGDTMPL(1))
   CASE (6)
     RADIUS = 6.3712E6
   CASE DEFAULT
     RADIUS = -9999.
 END SELECT

 RETURN

 END SUBROUTINE EARTH_RADIUS
