 SUBROUTINE IPXETAS(IDIR, GDTNUMI, GDTLEN, GDTMPLI, NPTS_INPUT,  &
                    BITMAP_INPUT, DATA_INPUT, GDTNUMO, GDTMPLO, &
                    NPTS_OUTPUT, BITMAP_OUTPUT, DATA_OUTPUT, IRET)
!$$$  SUBPROGRAM DOCUMENTATION BLOCK
!
! SUBPROGRAM:  IPXETAS    EXPAND OR CONTRACT ETA GRIDS
!   PRGMMR: IREDELL       ORG: W/NMC23       DATE: 96-04-10
!
! ABSTRACT: THIS SUBPROGRAM TRANSFORMS BETWEEN THE STAGGERED ETA GRIDS
!           AS USED IN THE ETA MODEL AND FOR NATIVE GRID TRANSMISSION
!           AND THEIR FULL EXPANSION AS USED FOR GENERAL INTERPOLATION
!           AND GRAPHICS.  THE ETA GRIDS ARE ROTATED LATITUDE-LONGITUDE
!           GRIDS STAGGERED AS DEFINED BY THE ARAKAWA E-GRID, THAT IS
!           WITH MASS DATA POINTS ALTERNATING WITH WIND DATA POINTS.
!           THE EXPANSION OF THE FIELDS IS DONE BY 4-POINT AVERAGING.
!
! PROGRAM HISTORY LOG:
!   96-04-10  IREDELL
!
! USAGE:    CALL IPXETAS(IDIR,M1,M2,KM,KGDS1,F1,KGDS2,F2,IRET)
!
!   INPUT ARGUMENT LIST:
!     IDIR     - INTEGER TRANSFORM OPTION
!                (+1 TO EXPAND STAGGERED MASS FIELDS TO FULL FIELDS)
!                (+2 TO EXPAND STAGGERED WIND FIELDS TO FULL FIELDS)
!                (-1 TO CONTRACT FULL MASS FIELDS TO STAGGERED FIELDS)
!                (-2 TO CONTRACT FULL WIND FIELDS TO STAGGERED FIELDS)
!     M1       - INTEGER SKIP NUMBER BETWEEN STAGGERED GRID FIELDS
!     M2       - INTEGER SKIP NUMBER BETWEEN FULL GRID FIELDS
!     KM       - INTEGER NUMBER OF FIELDS TO TRANSFORM
!     KGDS1    - INTEGER (200) GDS PARMS OF STAGGERED GRID IF IDIR>0
!     F1       - REAL (M1,KM) STAGGERED GRID FIELDS IF IDIR>0
!     KGDS2    - INTEGER (200) GDS PARMS OF FULL GRID IF IDIR<0
!     F2       - REAL (M2,KM) FULL GRID FIELDS IF IDIR<0
!
!   OUTPUT ARGUMENT LIST:
!     KGDS1    - INTEGER (200) GDS PARMS OF STAGGERED GRID IF IDIR<0
!     F1       - REAL (M1,KM) STAGGERED GRID FIELDS IF IDIR<0
!     KGDS2    - INTEGER (200) GDS PARMS OF FULL GRID IF IDIR>0
!     F2       - REAL (M2,KM) FULL GRID FIELDS IF IDIR>0
!     IRET     - INTEGER RETURN CODE
!                0    SUCCESSFUL TRANSFORMATION
!                1    IMPROPER GRID SPECIFICATION
!
! ATTRIBUTES:
!   LANGUAGE: FORTRAN 90
!
!$$$
 IMPLICIT NONE
!
 INTEGER, INTENT(IN   )            :: IDIR
 INTEGER, INTENT(IN   )            :: GDTNUMI, GDTLEN
 INTEGER(KIND=4), INTENT(IN   )    :: GDTMPLI(GDTLEN)
 INTEGER, INTENT(IN   )            :: NPTS_INPUT, NPTS_OUTPUT
 INTEGER, INTENT(  OUT)            :: GDTNUMO
 INTEGER(KIND=4), INTENT(  OUT)    :: GDTMPLO(GDTLEN)
 INTEGER, INTENT(  OUT)            :: IRET

 LOGICAL(KIND=1), INTENT(IN   )    :: BITMAP_INPUT(NPTS_INPUT)
 LOGICAL(KIND=1), INTENT(  OUT)    :: BITMAP_OUTPUT(NPTS_OUTPUT)

 REAL, INTENT(IN  )                :: DATA_INPUT(NPTS_INPUT)
 REAL, INTENT(OUT)                 :: DATA_OUTPUT(NPTS_OUTPUT)

 INTEGER                           :: SCAN_MODE, ISCALE, IP, IPOPT(20)
 INTEGER                           :: IBI(1), IBO(1), J, KM, NO

 REAL                              :: DLONS
 REAL, ALLOCATABLE                 :: OUTPUT_RLAT(:), OUTPUT_RLON(:)
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 IRET = 0
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
! ROUTINE ONLY WORKS FOR ROTATED LAT/LON GRIDS.
 IF (GDTNUMI/=1) THEN
   IRET=1
   RETURN
 ENDIF

 SCAN_MODE=GDTMPLI(19)
 IF((SCAN_MODE==68.OR.SCAN_MODE==72).AND.(IDIR<-2.OR.IDIR>-1))THEN
   GDTNUMO=GDTNUMI
   GDTMPLO=GDTMPLI
   GDTMPLO(19)=64
   GDTMPLO(8)=GDTMPLO(8)*2-1
   IF((GDTMPLO(8)*GDTMPLO(9))/=NPTS_OUTPUT)THEN
     IRET=3
     RETURN
   ENDIF
   ISCALE=GDTMPLO(10)*GDTMPLO(11)
   IF(ISCALE==0) ISCALE=1E6
   DLONS=FLOAT(GDTMPLO(17))/FLOAT(ISCALE)
   DLONS=DLONS*0.5
   GDTMPLO(17)=NINT(DLONS*FLOAT(ISCALE))
 ELSEIF(SCAN_MODE==64.AND.IDIR==-1)THEN  ! FULL TO H-GRID
   GDTNUMO=GDTNUMI
   GDTMPLO=GDTMPLI
   GDTMPLO(19)=68
   GDTMPLO(8)=(GDTMPLO(8)+1)/2
   IF((GDTMPLO(8)*GDTMPLO(9))/=NPTS_OUTPUT)THEN
     IRET=3
     RETURN
   ENDIF
   ISCALE=GDTMPLO(10)*GDTMPLO(11)
   IF(ISCALE==0) ISCALE=1E6
   DLONS=FLOAT(GDTMPLO(17))/FLOAT(ISCALE)
   DLONS=DLONS*2.0
   GDTMPLO(17)=NINT(DLONS*FLOAT(ISCALE))
 ELSEIF(SCAN_MODE==64.AND.IDIR==-2)THEN  ! FULL TO V-GRID
   GDTNUMO=GDTNUMI
   GDTMPLO=GDTMPLI
   GDTMPLO(19)=72
   GDTMPLO(8)=(GDTMPLO(8)+1)/2
   IF((GDTMPLO(8)*GDTMPLO(9))/=NPTS_OUTPUT)THEN
     IRET=3
     RETURN
   ENDIF
   ISCALE=GDTMPLO(10)*GDTMPLO(11)
   IF(ISCALE==0) ISCALE=1E6
   DLONS=FLOAT(GDTMPLO(17))/FLOAT(ISCALE)
   DLONS=DLONS*2.0
   GDTMPLO(17)=NINT(DLONS*FLOAT(ISCALE))
 ELSE
   IRET=2
   RETURN
 ENDIF

 KM=1
 IP=0
 IPOPT=0
 IBI=1
 IBO=0

 ALLOCATE(OUTPUT_RLAT(NPTS_OUTPUT))
 ALLOCATE(OUTPUT_RLON(NPTS_OUTPUT))

 CALL IPOLATES(IP, IPOPT, GDTNUMI, GDTMPLI, GDTLEN, &
               GDTNUMO, GDTMPLO, GDTLEN, &
               NPTS_INPUT, NPTS_OUTPUT, KM, IBI, BITMAP_INPUT, DATA_INPUT, &
               NO, OUTPUT_RLAT, OUTPUT_RLON, IBO, BITMAP_OUTPUT, DATA_OUTPUT, IRET)

 DEALLOCATE(OUTPUT_RLAT, OUTPUT_RLON)

 IF(IRET /= 0)THEN
   PRINT*,'- PROBLEM IN IPOLATES: ', IRET
   RETURN
 ENDIF

! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
! REPLACE ANY UNDEFINED POINTS ALONG THE LEFT AND RIGHT EDGES.
 DO J=1, GDTMPLO(9)
   BITMAP_OUTPUT(J*GDTMPLO(8))=BITMAP_OUTPUT(J*GDTMPLO(8)-1)
   DATA_OUTPUT(J*GDTMPLO(8))=DATA_OUTPUT(J*GDTMPLO(8)-1)
   BITMAP_OUTPUT((J-1)*GDTMPLO(8)+1)=BITMAP_OUTPUT((J-1)*GDTMPLO(8)+2)
   DATA_OUTPUT((J-1)*GDTMPLO(8)+1)=DATA_OUTPUT((J-1)*GDTMPLO(8)+2)
 ENDDO

 RETURN
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 END SUBROUTINE IPXETAS
