#!/bin/bash
 
#-----------------------------------------------------
# Script to run the copygb regression test on WCOSS-
# Phase 3 - Dell.
#
# Invoke this script as follows:
# "cat run.wcoss-dell.lsf | bsub"
#-----------------------------------------------------

#BSUB -oo copygb.log
#BSUB -eo copygb.log
#BSUB -q dev_shared
#BSUB -J copygb
#BSUB -R affinity[core(1)]
#BSUB -R rusage[mem=2500]
#BSUB -P GFS-T2O
#BSUB -W 3:00

set -x

module purge
module load EnvVars/1.0.2
module load ips/18.0.1.163
module load lsf/10.1

if [[ -d /gpfs/gp1/nco/ops/nwprod/fix ]]; then
  export NWPROD="/gpfs/gp1/nco/ops/nwprod/fix"
elif [[ -d /gpfs/tp1/nco/ops/nwprod/fix ]]; then
  export NWPROD="/gpfs/tp1/nco/ops/nwprod/fix"
else
  echo "Error. Cant find input directory"
  exit 2
fi

export REG_DIR="../.."

export WORK_DIR="/gpfs/dell1/stmp/$LOGNAME/regression"

$REG_DIR/copygb/scripts/copygb.ksh

exit 0
