#!/bin/ksh
 
#-----------------------------------------------------
# invoke this script as follows:
# bsub < run.wcoss.lsf
#-----------------------------------------------------

#BSUB -oo copygb.log
#BSUB -eo copygb.log
#BSUB -q dev_shared
#BSUB -J copygb
#BSUB -R affinity[core]
#BSUB -R rusage[mem=2500]
#BSUB -P GFS-MTN
#BSUB -W 3:00

set -x

. /usrx/local/Modules/3.2.9/init/ksh
module load ics/12.1
module load lsf/9.1

export REG_DIR="../.."

export WORK_DIR="/ptmp/$LOGNAME/regression"

$REG_DIR/copygb/scripts/copygb.ksh

exit 0
