#!/bin/sh
 
#----------------------------------------------------------
# Script to run the copygb regression test on WCOSS-Cray.
#
# Invoke this script as follows:
# "cat run.wcoss.cray.lsf | bsub"
#----------------------------------------------------------

#BSUB -oo copygb.log
#BSUB -eo copygb.log
#BSUB -q dev_shared
#BSUB -J copygb
#BSUB -R rusage[mem=2500]
#BSUB -P GFS-T2O
#BSUB -W 1:35

set -x

module list

export NWPROD="/gpfs/gp1/nco/ops/nwprod/fix"

export REG_DIR="../.."

export WORK_DIR="/gpfs/hps/ptmp/$LOGNAME/regression"

$REG_DIR/copygb/scripts/copygb.ksh

exit 0
