!!> @file
!! COMPUTE GAUSSIAN LATITUDES
!! @author IREDELL @date 92-04-16
!
!> COMPUTES COSINES OF COLATITUDE AND GAUSSIAN WEIGHTS
!!   ON THE GAUSSIAN LATITUDES.  THE GAUSSIAN LATITUDES ARE AT
!!   THE ZEROES OF THE LEGENDRE POLYNOMIAL OF THE GIVEN ORDER.
!!
!! PROGRAM HISTORY LOG:
!! -  92-04-16  IREDELL
!! -  97-10-20  IREDELL  INCREASED PRECISION
!! - 1999-08-18  IREDELL  CALLED SPLAT
!!
!! @param JMAX     - INPUT NUMBER OF LATITUDES.
!! @param[out] SLAT     - REAL (K) COSINES OF COLATITUDE.
!! @param[out] WLAT     - REAL (K) GAUSSIAN WEIGHTS.
!!
!! SUBPROGRAMS CALLED:
!! - SPLAT()        COMPUTE LATITUDE FUNCTIONS
!!
SUBROUTINE GAUSSLAT(JMAX,SLAT,WLAT)
 IMPLICIT NONE

 INTEGER,           INTENT(IN   ) :: JMAX
 REAL,              INTENT(OUT  ) :: SLAT(JMAX),WLAT(JMAX)

 CALL SPLAT(4,JMAX,SLAT,WLAT)

 RETURN
 END SUBROUTINE GAUSSLAT
