 SUBROUTINE GDSAWT(KGDS,KB,KA,XPTS,YPTS,RLAT,RLON,AWT)
!$$$  SUBPROGRAM DOCUMENTATION BLOCK
!
! SUBPROGRAM:  GDSAWT     GRID DESCRIPTION SECTION AREA WEIGHTS
!   PRGMMR: IREDELL       ORG: W/NMC23       DATE: 96-04-10
!
! ABSTRACT: THIS SUBPROGRAM DECODES THE GRIB GRID DESCRIPTION SECTION
!           AND RETURNS THE EARTH'S AREA COVERED BY EACH GRID POINT.
!           THE GRID AND EARTH COORDINATES ARE ALSO RETURNED.
!           EDGE POINTS AND CORNER POINTS ARE GIVEN FULL WEIGHT NOW.
!
! PROGRAM HISTORY LOG:
!   96-04-10  IREDELL
!   97-10-20  IREDELL  MADE OBSOLESCENT BY GDSWZD
!
! USAGE:    CALL GDSAWT(KGDS,KB,KA,XPTS,YPTS,RLAT,RLON,AWT)
!
!   INPUT ARGUMENT LIST:
!     KGDS     - INTEGER (200) GDS PARAMETERS AS DECODED BY W3FI63
!     KB       - INTEGER MAXIMUM NUMBER OF COORDINATES
!
!   OUTPUT ARGUMENT LIST:
!     KA       - INTEGER NUMBER OF VALID POINTS COMPUTED
!     XPTS     - REAL (KB) GRID X POINT COORDINATES
!     YPTS     - REAL (KB) GRID Y POINT COORDINATES
!     RLON     - REAL (KB) EARTH LONGITUDES IN DEGREES
!     RLAT     - REAL (KB) EARTH LATITUDES IN DEGREES N
!     AWT      - REAL (KB) AREA WEIGHTS IN M**2
!
! SUBPROGRAMS CALLED:
!   GDSWZD       GRID DESCRIPTION SECTION WIZARD
!
! ATTRIBUTES:
!   LANGUAGE: FORTRAN 90
!
!$$$
 IMPLICIT NONE
!
 INTEGER,      INTENT(IN   ) :: KGDS(200)
 INTEGER,      INTENT(IN   ) :: KB
 INTEGER,      INTENT(  OUT) :: KA
!
 REAL,         INTENT(  OUT) :: XPTS(KB),YPTS(KB)
 REAL,         INTENT(  OUT) :: RLAT(KB),RLON(KB),AWT(KB)
!
 REAL                        :: CROT(KB),SROT(KB),FILL
 REAL                        :: XLON(KB),XLAT(KB),YLON(KB),YLAT(KB)
!
 FILL=-9999.
 CALL GDSWZD(KGDS,0,KB,FILL,XPTS,YPTS,RLON,RLAT,KA,  &
             0,CROT,SROT,1,XLON,XLAT,YLON,YLAT,AWT)
!
 END SUBROUTINE GDSAWT
